<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Employee_fa fa-sign-in fa-3</name>
   <tag></tag>
   <elementGuidId>12c28dc0-149a-4460-be5c-c5b6d0540859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='stdForm']/a/div/div[2]/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-sign-in.fa-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>fd1fb858-4b16-463c-b41a-e933bc6e3ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-sign-in fa-3</value>
      <webElementGuid>25df0a92-8eb9-499e-a50b-a6d6032e3e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>65963a26-1cfc-437c-913a-dc320df7f0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stdForm&quot;)/a[@class=&quot;text-decoration-none&quot;]/div[@class=&quot;d-flex jusitfy-content-start align-items-stretch&quot;]/div[@class=&quot;flex-grow-1&quot;]/button[@class=&quot;btn btn-primary fw-bold&quot;]/i[@class=&quot;fa fa-sign-in fa-3&quot;]</value>
      <webElementGuid>5b4f048e-3f63-4b63-8a8a-6b3ae995ed57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='stdForm']/a/div/div[2]/button/i</value>
      <webElementGuid>dab2ae7c-c79e-4b94-80c2-d58e918d9632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>230b2bec-0f75-4782-b6e3-c36ef318fc87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='empForm']/a/div/div[2]/button/i</value>
      <webElementGuid>6aee8707-4c82-4186-a1a0-4bffe8ef4ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/a/div/div[2]/button/i</value>
      <webElementGuid>ea4b9d8e-5e6e-4885-adb8-569e94c33ede</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
