<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(html1bodyclass, , WhiteBackgr_bc236d</name>
   <tag></tag>
   <elementGuidId>b00d4f49-b274-4021-a4c6-909b567be219</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-slbtlrvido02']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-slbtlrvido02&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;c-slbtlrvido02&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9451e39c-bb21-4498-b3ee-f53f8a233df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>7805d2b0-465d-452f-b123-6deb275fabdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-slbtlrvido02</value>
      <webElementGuid>2281c52f-43a5-49b6-9354-aafebdced930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>32e555e2-df50-443a-8754-a0799f151dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>12ca8d46-278c-4951-8c39-a9a832f410e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>2349f896-f7ed-4bd5-ab1b-7b2ebd0048b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=QoukH5jSO3sKFzVEA7Vc8VgC&amp;k=6LfzijMUAAAAACRHPUtzyKDeqEtqSmWOuJS3duAj</value>
      <webElementGuid>91d8a44e-6304-44ad-a04a-55ceed5ff557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;WhiteBackground&quot;]/div[5]/div[2]/iframe[1]</value>
      <webElementGuid>4a4e9a26-a021-4afe-8494-113e01fd2e79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-slbtlrvido02']</value>
      <webElementGuid>6c9cd637-bf03-4572-a016-66ec7d94a837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>9ce5ff3b-6e68-48d9-8d3f-7d463c0fbc4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @name = 'c-slbtlrvido02' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=QoukH5jSO3sKFzVEA7Vc8VgC&amp;k=6LfzijMUAAAAACRHPUtzyKDeqEtqSmWOuJS3duAj']</value>
      <webElementGuid>8050ef0b-6210-4036-83db-960869e56e65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
