<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_stairs_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>3620e6e7-4546-4515-b071-c9b86e638a24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.rc-imageselect-tile >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>30d22480-5577-4168-b337-b5cd3cf02afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>cae337b1-1f04-4614-aa7e-44db961db60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5DgG4mRfvLxhELisUwGHgIWvgP1kz3bUpO4PXki-WSwYlnhwYvdnEGOzkiDXcy1IA5dtnXg8a6yxhfSMJQdLOKelyQxuhIoJWXy4klNf3tL9qy53-a2ulBPOm6q1LFlX4PCaqMKyfTVBbRnVxD65jLlwep9EtGng1MwET7HccpxIkBbQXVhhigDoL3_f9uKvOahl6SgsbCScl2ZWgsorj_suOiUhKSGaeAPV15DnIxedKTL7E&amp;k=6LfzijMUAAAAACRHPUtzyKDeqEtqSmWOuJS3duAj</value>
      <webElementGuid>18dc0bc6-b168-4a9b-b025-aa82cb4551ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>2cbb5f46-42fc-4207-95f2-c2b20b615d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CrossBrowser/Page_VIT Vellore - VTOP/iframe_concat(html1bodyclass, , WhiteBackgr_bc236d</value>
      <webElementGuid>682f0299-6188-4deb-883c-9ac0d8027124</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      <webElementGuid>e0e948c7-9d9c-4296-8ab4-e3d21679eb32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5DgG4mRfvLxhELisUwGHgIWvgP1kz3bUpO4PXki-WSwYlnhwYvdnEGOzkiDXcy1IA5dtnXg8a6yxhfSMJQdLOKelyQxuhIoJWXy4klNf3tL9qy53-a2ulBPOm6q1LFlX4PCaqMKyfTVBbRnVxD65jLlwep9EtGng1MwET7HccpxIkBbQXVhhigDoL3_f9uKvOahl6SgsbCScl2ZWgsorj_suOiUhKSGaeAPV15DnIxedKTL7E&amp;k=6LfzijMUAAAAACRHPUtzyKDeqEtqSmWOuJS3duAj')]</value>
      <webElementGuid>0888077c-2a4e-416b-8f56-c102decd64b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>b34324bd-1a79-4949-9f34-0d62ad0b64a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5DgG4mRfvLxhELisUwGHgIWvgP1kz3bUpO4PXki-WSwYlnhwYvdnEGOzkiDXcy1IA5dtnXg8a6yxhfSMJQdLOKelyQxuhIoJWXy4klNf3tL9qy53-a2ulBPOm6q1LFlX4PCaqMKyfTVBbRnVxD65jLlwep9EtGng1MwET7HccpxIkBbQXVhhigDoL3_f9uKvOahl6SgsbCScl2ZWgsorj_suOiUhKSGaeAPV15DnIxedKTL7E&amp;k=6LfzijMUAAAAACRHPUtzyKDeqEtqSmWOuJS3duAj']</value>
      <webElementGuid>812c3c2b-d87f-425a-9cab-34934e43c517</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
