<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_cars_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>fe7d977a-e16f-4e77-b2ee-fd745370eb4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>td:nth-child(2) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>311a699b-20b5-42fa-b470-2abc30c498a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>1016926f-97c9-45b6-9200-6a28f8910905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6P9OqwTq0E15xeYsq8LvpXfF9qqdRKeDT_oCG2Ipmo-7qCDqVHB6rIV_q2vu8Qabff-nmlHU8Pn2_vpsKZzM5ii2pY3h3DTPpSfGB1T-pRyrylcLmNkRcndgkSp6rdci5IZ_TsoGSCTjpdlMkqDXlU-qvKXNCuF_k_Vma48jXftwa2dUTE2U9j4Br_Lx4Ctx0FRstRC-s85ct6Rbwzr_AY6HcLZdlZH598BM4zQRku83Qv4w4&amp;k=6LfzijMUAAAAACRHPUtzyKDeqEtqSmWOuJS3duAj</value>
      <webElementGuid>e16abbaf-be6d-4796-b1ee-059f3c840423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>072b0fa4-0bfe-4671-bb74-7c7e395c2efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CrossBrowser/Page_VIT Vellore - VTOP/iframe_concat(html1bodyclass, , WhiteBackgr_bc236d</value>
      <webElementGuid>ae0a9533-347b-4407-80d9-6c3b25c6d5a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      <webElementGuid>1b59260b-0c6d-4ce3-9ba8-6300852f2283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6P9OqwTq0E15xeYsq8LvpXfF9qqdRKeDT_oCG2Ipmo-7qCDqVHB6rIV_q2vu8Qabff-nmlHU8Pn2_vpsKZzM5ii2pY3h3DTPpSfGB1T-pRyrylcLmNkRcndgkSp6rdci5IZ_TsoGSCTjpdlMkqDXlU-qvKXNCuF_k_Vma48jXftwa2dUTE2U9j4Br_Lx4Ctx0FRstRC-s85ct6Rbwzr_AY6HcLZdlZH598BM4zQRku83Qv4w4&amp;k=6LfzijMUAAAAACRHPUtzyKDeqEtqSmWOuJS3duAj')])[2]</value>
      <webElementGuid>7dc1d80b-eb91-4ba9-b4d9-277a70c20d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/img</value>
      <webElementGuid>ee6cd73b-ba9e-4493-9dba-65a6bd0f3b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6P9OqwTq0E15xeYsq8LvpXfF9qqdRKeDT_oCG2Ipmo-7qCDqVHB6rIV_q2vu8Qabff-nmlHU8Pn2_vpsKZzM5ii2pY3h3DTPpSfGB1T-pRyrylcLmNkRcndgkSp6rdci5IZ_TsoGSCTjpdlMkqDXlU-qvKXNCuF_k_Vma48jXftwa2dUTE2U9j4Br_Lx4Ctx0FRstRC-s85ct6Rbwzr_AY6HcLZdlZH598BM4zQRku83Qv4w4&amp;k=6LfzijMUAAAAACRHPUtzyKDeqEtqSmWOuJS3duAj']</value>
      <webElementGuid>b61d931f-ff5a-4b57-aad9-50d4444b4cdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
